### PR TITLE
Regex only with MatrixPart and rerun only run where the regex is found

### PR DESCRIPTION
**Pull request by Neo-Burner**

### CODE REVIEW

**Comment by KostyaSha** [comment]
Why the whole class replaced? Is it indentation changes?

**Comment by KostyaSha** [comment]
Tests broken

**Comment by Neo-Burner** [comment]
Effectively indentation changes, sorry :(

If I have the time, i'll take a look on tests broken.

**Comment by ikedam** [comment]
I believe this is same to #17 , and can be replaced with #21.

**Comment by ikedam** [comment]
Merged #21 instead.

**Pull request closed without merging**
