### PR TITLE
Rebaseline Jenkins to 2.375.4

### PR DESCRIPTION
**Pull request by sghill-rewrite**
2.375.4 is now the lowest [recommended version](
https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions)

Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/4ZZ3Z

### CODE REVIEW

**Comment by sghill** [comment]
@ikedam could you take a look at this one when you get a chance?

**Review by ikedam — APPROVED** [review]
@sghill-rewrite 
Looks good to me. Sorry for my really late response.

Would you let me know the motivation or the context of this update?

If you want to have naginator-plugin continue to catch up the recommended jenkins version, it would be better to have you take over maintaining this plugin.

Unfortunately I don't plan to maintain this plugin so often or catch up latest Jenkins  versions.
(I suppose there would be convenient ways to automatically release new plugin versions every time when recommended version is updated, but I don't have time for now)

**Comment by sghill** [comment]
Hi @ikedam!

(sghill-rewrite is my bot)

My motivation is I run several Jenkins servers where this plugin is installed. Keeping up-to-date means we can react to deprecations and library changes early, making upgrades safer.

Rebaselining also means fewer plugins installed. As Jenkins factors out core functionality into plugins, it starts implicitly installing those plugins for anything with an older baseline. These eventually fall out of date and add to the maintenance load.

Happy to take over maintenance if that's what you'd prefer.

For transparency all I plan to do is [enable CD releases](https://www.jenkins.io/doc/developer/publishing/releasing-cd/), automate these updates, and publish quarterly.

**Comment by ikedam** [comment]
@sghill
OK. So you want CD for naginator-plugin and you'd better to take over maintenance of this plugin.
Would you proceed adoption process following https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/#plugins-marked-for-adoption ?

Unfortunately I don't have full privilege for this repository and can't mark this plugin for adoption (can't add `adopt-this-plugin` label to this repository). But I believe the request will be approved by referring this comment instead.

**Pull request merged**
