### PR TITLE
Allow copy badge action.

### PR DESCRIPTION
**Pull request by KostyaSha**
#34 

While there is no better way do String based comparison.
This excludes unneded reverse dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/naginator-plugin/36)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@ikedam @oleg-nenashev

**Comment by ikedam** [comment]
-1
naginator-plugin have to know every classes that someone want to preserve and requires updates and new releases everytime some plugin get want its action preserved.

**Comment by KostyaSha** [comment]
Adding something in core would require half year, creating additional plugin one inteface (and interface as marker is bad pattern) is stupid. Job-dsl has plugin specific things and handle it without any problems.

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/buildtriggerbadge-plugin/blob/master/src/main/java/org/jenkinsci/plugins/buildtriggerbadge/IconFinder.java#L65

**Comment by sghill** [comment]
Closing due to inactivity.

**Pull request closed without merging**
