### PR TITLE
RequirePOST on Retry Action

### PR DESCRIPTION
**Pull request by sghill**
Adds the `RequirePOST` annotation to `doIndex` for the `retry` action.
Suppresses warnings for the permission check and csrf on static data.
This is a followup to #109. Would appreciate confirmation this is the correct way to fix these issues by @strangelookingnerd.

### Testing done

Existing tests pass.
Viewed the results of `RequirePOST` in the UI.

2024-06-25-naginator-retry-post

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by strangelookingnerd — APPROVED** [review]
LGTM 👍🏼

**Comment by mawinter69** [comment]
caused https://issues.jenkins.io/browse/JENKINS-73378 as the sidepanel link is not adjusted to do a post request

**Comment by sghill** [comment]
@mawinter69 I had a quick look at this, but I'm not sure how to update that sidepanel link.

If you could share an example of making this a post, or wanted to send in a PR, I'd be happy to publish a new release with the fix.

**Comment by mawinter69** [comment]
You will need to create an action.jelly with following content
```
<?jelly escape-by-default='true'?>
<j:jelly xmlns:j="jelly:core" xmlns:l="/lib/layout">
    <j:if test="${action.urlName != null}">
        <l:task icon="${action.iconFileName}" title="${action.displayName}" href="${rootURL}/${it.url}${action.taskUrl}/" post="true"/>
    </j:if>
</j:jelly>
```

**Comment by sghill** [comment]
Unfortunately haven't had much luck with this.

I searched and found the rebuild plugin's [action.jelly](https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/resources/com/sonyericsson/rebuild/AbstractRebuildAction/action.jelly) looks very similar, but it has a `getTaskUrl()` [defined](https://github.com/jenkinsci/rebuild-plugin/blob/master/src/main/java/com/sonyericsson/rebuild/RebuildAction.java#L126) in that class. I was able to get a bit farther by adding the `retry/` url:

```xml
<?jelly escape-by-default='true'?>
<j:jelly xmlns:j="jelly:core" xmlns:l="/lib/layout">
    <j:if test="${action.urlName != null}">
        <l:task icon="${action.iconFileName}" title="${action.displayName}" href="${rootURL}/${it.url}retry/" post="true"/>
    </j:if>
</j:jelly>
```

But the requests are all `fetch`, so the browser isn't actually following the redirect. This example is from clicking the `Retry` button on `projectabc/14`. Build 15 is created, but we're left on build 14's page.
Screenshot 2024-07-01 200553

**Comment by mawinter69** [comment]
If you want to retain the old behaviour of getting redirected to the job page after clicking the retry link you will need to write some javascript that overrides the default behaviour of calling fetch in js. You can use the data-callback from `l:task` for this (see https://reports.jenkins.io/core-taglib/jelly-taglib-ref.html#layout:task, requires at least 2.437).
Alternatively you put a form inside the action.jelly and a link sinde the form, but you will still need to some javascript to submit the form when clicking the link.
Probably both approaches have the problem that they will not work in the contextmenu (haven't verified this).
Or you live with the change in behaviour that you no longer get redirected to the job page, but context menu still works.

**Pull request merged**
