### PR TITLE
Preserve BadgeActions

### PR DESCRIPTION
**Pull request by KostyaSha**
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/naginator-plugin/34)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@ikedam could you review?

**Comment by oleg-nenashev** [comment]
@KostyaSha could you please clarify the use-case? AFAIK the most of the badges are being injected by extensions during the build execution.

**Comment by KostyaSha** [comment]
And not most injecting during trigering, i.e. https://github.com/KostyaSha/github-pullrequest-plugin :)

**Comment by ikedam** [comment]
-1
Some build badges are conditionally added during builds or after builds.
Those badges should not be added when builds start.

Example: [PromotedBuildAction in promoted-builds-plugin](https://github.com/jenkinsci/promoted-builds-plugin/blob/adfdf61f362fb79cf2e04c14524f460a4d2f41d2/src/main/java/hudson/plugins/promoted_builds/PromotedBuildAction.java). It's added when a build is promoted. This change results a badge is displayed for a build that isn't actually promoted.

It's a bad idea to copy general actions as we can't know how those actions are actually used.

On the other hands, plugins may want their own actions copied when a build is retriggered (e.g. [JENKINS-29765](https://issues.jenkins-ci.org/browse/JENKINS-29765) ).
And it's not reasonable to include all those plugins to optional dependencies of naginator-plugin.

How about this way?:
* Create a new interface "CopyAtRestartAction"
* If a plugin want to have their actions reproduced when retrigger a build, they should implement "CopyAtRestartAction".
* naginator copies all actions implementing "CopyAtRestartAction".

I believe "CopyAtRestartAction" should be provided not by naginator-plugin, but by Jenkins core or a new tiny plugin, as it's useful not only for naginator-plugin but also for rebuild-plugin.

**Comment by KostyaSha** [comment]
As usual pure api.

**Comment by KostyaSha** [comment]
Temporary i can add text file with whitelisted classes.

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/naginator-plugin/pull/36

**Pull request closed without merging**
